kind: pipeline
name: test

workspace:
    base: /go
    path: src/github.com/saguywalker/go-with-drone

steps:
- name: format
  image: golang
  commands:
    - go fmt $(go list ./... | grep -v /vendor/)
    - go vet $(go list ./... | grep -v /vendor/)

- name: test-func
  image: golang
  commands:
    - go test

---
kind: pipeline
name: build

workspace:
    base: /go
    path: src/github.com/saguywalker/go-with-drone
    
steps:
- name: compile
  image: golang
  commands:
    - go build main.go
      #    - git config --global user.email "saguywalker@protonmail.com"
      #- git config --global user.name "saguywalker"
      #- git add main
      #- git commit -m "Commit main"
      #- git remote add origin ${DRONE_GIT_SSH_URL}
      #- git push origin master

depends_on:
- test

---
kind: pipeline
name: deploy

workspace:
    base: /go
    path: src/github.com/saguywalker/go-with-drone

steps:
- name: commit-output
  image: golang
  commands:
    #- git config --global user.email "saguywalker@protonmail.com"
    #- git config --global user.name "saguywalker"
     - mkdir -p results
    - ls -la
    - ./main -commit=${DRONE_COMMIT_SHA} > results/output
      #- git rm main
      #- git add *
      #- git commit -m "[CI] Add output to master branch."
      #- git remote add origin ${DRONE_GIT_SSH_URL}
      #- git push origin HEAD:master

- name: run
  image: golang
  commands:
    - cat results/output

depends_on:
- build
